### ISSUE TITLE
Berksfile on OpsWorks

### ISSUE THREAD

**Issue by sealabcore** [joeyAghion/opsworks_delayed_job#8]
How do you get around this dependency issue when using a Berksfile on Opsworks and including these recipes?

```
STDOUT: Resolving cookbook dependencies...
Fetching 'kit-chef' from source at .
Fetching 'opsworks_delayed_job' from git://github.com/joeyAghion/opsworks_delayed_job.git (at master)
Fetching 'papertrail' from git://github.com/firstbanco/chef-papertrail.git (at master)
Fetching cookbook index from https://supermarket.getchef.com...
STDERR: Unable to satisfy constraints on package deploy, which does not exist, due to solution constraint (opsworks_delayed_job = 0.5.0). Solution constraints that may result in a constraint on deploy: [(opsworks_delayed_job = 0.5.0) -> (deploy >= 0.0.0)]
Missing artifacts: deploy
Demand that cannot be met: (opsworks_delayed_job = 0.5.0)
Unable to find a solution for demands: cron (>= 0.0.0), kit-chef (0.1.0), opsworks_delayed_job (0.5.0), papertrail (0.0.2), postgresql (~> 3.4.2)
---- End output of /opt/aws/opsworks/local/bin/berks vendor /opt/aws/opsworks/current/berkshelf-cookbooks ----
Ran /opt/aws/opsworks/local/bin/berks vendor /opt/aws/opsworks/current/berkshelf-cookbooks returned 106 
```

**Comment by erupenkman** [comment]
this was killing me but have a workaround. first add opsworks-cookbooks as a submodule (using chef 11.10)

     git submodule add -b release-chef-11.10  https://github.com/aws/opsworks-cookbooks.git opsworks/cookbooks

then in `Berksfile` add all of their dependencies 
source "https://supermarket.getchef.com"
cookbook "deploy", path: 'opsworks/cookbooks/deploy'
cookbook "opsworks_commons", path: 'opsworks/cookbooks/opsworks_commons'
cookbook "scm_helper", path: 'opsworks/cookbooks/scm_helper'
cookbook "mod_php5_apache2", path: 'opsworks/cookbooks/mod_php5_apache2'
cookbook "ssh_users", path: 'opsworks/cookbooks/ssh_users'
cookbook "opsworks_agent_monit", path: 'opsworks/cookbooks/opsworks_agent_monit'
cookbook "opsworks_java", path: 'opsworks/cookbooks/opsworks_java'
cookbook "opsworks_aws_flow_ruby", path: 'opsworks/cookbooks/opsworks_aws_flow_ruby'
cookbook "gem_support", path: 'opsworks/cookbooks/gem_support'
cookbook "opsworks_nodejs", path: 'opsworks/cookbooks/opsworks_nodejs'
cookbook "opsworks_initial_setup", path: 'opsworks/cookbooks/opsworks_initial_setup'
cookbook "mysql", path: 'opsworks/cookbooks/mysql'
cookbook "dependencies", path: 'opsworks/cookbooks/dependencies'
cookbook "opsworks_ganglia", path: 'opsworks/cookbooks/opsworks_ganglia'

**Comment by joe1chen** [comment]
We are also seeing the same errors

```
================================================================================
Recipe Compile Error in /var/lib/aws/opsworks/cache.stage2/cookbooks/packages/attributes/packages.rb
================================================================================


TypeError
---------
no implicit conversion of Symbol into Integer


Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/packages/attributes/packages.rb:19:in `from_file'
```

@rposborne Can you describe how you resolved the issue and what it had to do with caching?

**Comment by aadamson** [comment]
@rposborne I'm seeing the same issue that you ran into. Can you elaborate on how you solved it?

**Comment by dogomedia** [comment]
@aadamson The underlying issue is that the metadata.rb contains this line ```depends 'deploy'```.  Instead of depending on the AWS Opworks deploy cookbook, it pulls in the deploy cookbook from the Chef supermarket.  Forking and removing the dependency might work.

**Comment by aadamson** [comment]
I was referring to the issue with "default[:packages][:dist_only] = false"
causing an implicit conversion error. Is there a workaround for that?

**Comment by joeyAghion** [comment]
Sorry to come back to this only after so long.

The dependency on Opsworks' `deploy` cookbook was necessary because, without it, the custom cookbook would fail when it tried to `include_recipe 'deploy'`. _However_ that seems to no longer be the case, at least on Chef 11.10.

The latest version of this cookbook (v0.7) removes the dependency (14829c984d7bb0fdf1f5a973d6a4d0d49c755a59).
