### ISSUE TITLE
Workers not reloading on Deploy

### ISSUE THREAD

**Issue by robamaton** [joeyAghion/opsworks_delayed_job#9]
After deploying an application, the workers are still working off the previous code, so I have to stop the workers myself after the deploy. It seems this would make sense to be built into the deploy recipe in this project. Is this as issue on my end? Or would a PR with this added functionality be appreciated?

**Comment by joeyAghion** [comment]
Closed via https://github.com/joeyAghion/opsworks_delayed_job/pull/10. Available starting in v0.6 of the cookbook.
